# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PerformanceSettings' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerformanceSettings
  pod 'DynamsoftBarcodeReaderBundle','10.2.1100'

end
