# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DecodeFromAnImageObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DecodeFromAnImageObjc
  pod 'DynamsoftBarcodeReader','10.0.20'
  pod 'DynamsoftCaptureVisionRouter','2.0.20'

end
