# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DecodeFromAnImageObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DecodeFromAnImageObjc
  pod 'DynamsoftCore','3.2.30'
  pod 'DynamsoftImageProcessing','2.2.30'
  pod 'DynamsoftLicense','3.2.20'
  pod 'DynamsoftBarcodeReader','10.2.11'
  pod 'DynamsoftCaptureVisionRouter','2.2.30'

end
