# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TinyBarcodeDecoding' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TinyBarcodeDecoding
  pod 'DynamsoftBarcodeReaderBundle','10.2.1101'

end
