# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageDecodingObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageDecodingObjc
  pod 'DynamsoftBarcodeReader','9.6.10'

end
