# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorldObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorldObjC
pod 'DynamsoftCameraEnhancer','2.1.3'
pod 'DynamsoftBarcodeReader','9.0.0'

end
