# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReadADriversLicense' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReadADriversLicense
  pod 'DynamsoftCameraEnhancer','2.3.12'
  pod 'DynamsoftBarcodeReader','9.6.20'

end
