# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReadADriversLicense' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReadADriversLicense
pod 'DynamsoftCameraEnhancer','2.1.0'
pod 'DynamsoftBarcodeReader','8.9.0'

end
