# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PerformanceSettingsObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerformanceSettingsObjC
pod 'DynamsoftCameraEnhancer','2.3.1'
pod 'DynamsoftBarcodeReader','9.2.11'

end
