# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PerformanceSettingsSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerformanceSettingsSwift
pod 'DynamsoftCameraEnhancer','2.1.1'
pod 'DynamsoftBarcodeReader','8.9.1'

end
