# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DecodeWithCameraEnhancerObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DecodeWithCameraEnhancerObjc
  pod 'DynamsoftCore','3.0.20'
  pod 'DynamsoftImageProcessing','2.0.21'
  pod 'DynamsoftLicense','3.0.30'
  pod 'DynamsoftBarcodeReader','10.0.21'
  pod 'DynamsoftCaptureVisionRouter','2.0.21'
  pod 'DynamsoftCameraEnhancer','4.0.2'

end
