# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorldSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorldSwift
  pod 'DynamsoftCameraEnhancer','2.3.22'
  pod 'DynamsoftBarcodeReader','9.6.40'

end
